### PR TITLE
Upgrade to `league/flysystem` ^2

### PR DESCRIPTION
**Pull request by drupol**
Hello,

I might be using this project for a custom project of mine using `league/flysystem` 2.

Then, I refactored/upgraded it for flysystem 2 and almost got all the tests working.

In order to not loose this work, I'm submitting here my pull request containing all the changes, separated per commits.

What has been done:

* Works with Flysystem 2
* Normalized composer.json
* Removed the `$size` parameter: use `writeStream` for large objects, use `write` for regular objects.
* Removed a bunch of custom methods
* Update the tests
* Added grumphp checks
* Update Github Actions

Let me know what you think, I can still dedicate some time to it if necessary.

Thanks!

@ajmitch  It might be interesting for you, I took some of your code in the PR.

### CODE REVIEW

**Comment by Dallas62** [comment]
Hi @mzur,
Supporting v2 of Flysystem would be really appreciated.
The current version of `flysystem-openstack-swift` is blocking update of dependencies to v1.
Regards

**Comment by miclf** [comment]
Flysystem 3 got released a few days ago: https://blog.frankdejonge.nl/flysystem-3-0-0-is-released/

That said, breaking changes seem to be minimal between `2.x` and `3.x`, so I guess most of the work you’ve done is still relevant, @drupol

**Comment by drupol** [comment]
There is absolutely no support from the maintainer so I guess I won't invest time anymore in this... Sorry.

**Comment by drupol** [comment]
Cool, is this package still maintained ? Got no feedback from the maintainer so far...

**Comment by mzur** [comment]
I'm not the maintainer but I've read your message. Although I'm interested that this package still exists, I have only little time to spare. I'll come around to this PR eventually but it may take a while. Until then feel free to live-test your changes in a fork. Maybe you can find some issues or you can report that everything works fine.

**Comment by drupol** [comment]
Sorry mate, I don't have any more time and reasons to dedicate time to this project at the moment, however, I would gladly accept sponsors for doing it.

**Comment by mzur** [comment]
Thanks for your work @drupol. I modified the PR to take a more conservative approach with less dependencies. It's now possible to use `writeStream` without creating large objects in all cases.

Breaking changes:
- Requires PHP >= 7.4
- `write` can't be used to create large objects any more.
- 'createDirectory' throws an exception, as this is not supported by Swift.

Other notes:
- The method signatures are now changed according to Flysystem 2. Most do not return a value any more but throw an exception in case something went wrong.
- The following methods are unsupported: `createDirectory`, `visibility` and `setVisibility`.

**Comment by drupol** [comment]
Cool ! Thanks for partially incorporating my changes, good luck with the project!

**Pull request merged**
