### PR TITLE
Fix deleteDir removes other files/dirs #19

### PR DESCRIPTION
**Pull request by jeroenlammerts**
@chrisnharvey this is my suggestion how this can be fixed. Please verify if this is the way to go.

### CODE REVIEW

**Comment by mzur** [comment]
Please fix the failing test in `SwiftAdapterTest::testDeleteDir`.

**Comment by chrisnharvey** [comment]
@jeroenlammerts Thanks for this. Could you fix the failing test, then we can merge and tag a new version.

@mzur I have replaced Travis with Github actions.

**Comment by jeroenlammerts** [comment]
For reference, this is the underlying API call to list the objects in the dir to delete. I tried if the path parameter would work for this case, but this doesn't list subdirs.

https://docs.openstack.org/api-ref/object-store/?expanded=show-container-details-and-list-objects-detail#show-container-details-and-list-objects

**Comment by jeroenlammerts** [comment]
@chrisnharvey can this be merged?

**Pull request merged**
